### ISSUE TITLE
OS Crashes and Automatically Reboots When Downloading Large Torrents with qBitTorrent or Deluge on Nightly Build 20240424

### ISSUE THREAD

**Issue by egigoka** [gnumdk-mobile/miatoll-issues#2]
**Issue Description:**  
After updating to the latest nightly community build (version 20240424, updated with `apt dist-upgrade`), the entire operating system crashes and automatically reboots when I start downloading large torrents using qBitTorrent or Deluge. This crash consistently happens with larger files (e.g., 4 GiB), while smaller files (e.g., 700 MiB) may occasionally complete successfully but still cause crashes in most attempts. Initially, the system and all applications operate as expected, but as soon as a substantial download starts, the system becomes unresponsive and reboots on its own. This issue does not occur when using Transmission, which can download files of any size without causing the OS to crash.

**Steps to Reproduce:**
1. Flash the latest nightly community build (20240424) onto the device.
2. Apply system updates using `sudo apt dist-upgrade`.
3. Open qBitTorrent or Deluge and configure if necessary.
4. Attempt to reset qBitTorrent by deleting any folder under `/home/droidian` that contains the name "qBitTorrent."
5. Attempt to download a torrent, particularly larger ones around 4 GiB.

**Expected Behavior:**  
qBitTorrent and Deluge should be able to download files of any size without causing system instability or crashes. The OS should remain stable and responsive during these operations.

**Actual Behavior:**  
The OS crashes and automatically reboots when attempting to download large torrents using qBitTorrent or Deluge. Smaller torrents may occasionally complete, but the success rate is low (about 1 in 10 tries for a 700 MiB file). Transmission does not cause these crashes and operates normally.

**Environment:**
- **Nightly Build Version:** 20240424 (updated with `apt dist-upgrade`)
- **Device Model:** Xiaomi Redmi Note 9S (global) - miatoll, curtana
- **Applications:** qBitTorrent, Deluge (crashing), Transmission (working)

**Troubleshooting Steps Attempted:**
- Successfully downloaded a 700 MiB torrent once out of multiple attempts; larger torrents (4 GiB) cause the system to crash and reboot every time.
- Initially suspected and disabled mounting of the microSD card, directing downloads to the eMMC to rule out storage issues.
- Nuked every folder in `/home/droidian` that contains the name "qBitTorrent" to reset the application to default settings.
- Disabled the `syncthing` systemd unit to eliminate it as a potential cause.
- Confirmed stable network performance with speeds up to 300 MiB/s, and tested using both Wi-Fi and a 4G hotspot, which both led to crashes.
- Planned to test on a freshly installed build.

**Additional Information:**
- Restored the `/home/droidian` folder from the official version to the community-maintained build to preserve app settings and data, which might be influencing the instability.
- System logs include errors related to PulseAudio and missing libraries for graphics drivers, but no direct indications of what causes the crashes during torrent downloads with qBitTorrent or Deluge.

*This issue text was refined with the assistance of ChatGPT. English is not my first language, so the enhancements aimed to make the description more coherent and structured.*

Journalctl log: [pastebin](https://pastebin.com/TwuJL42e)

**Comment by gaussandhisgun** [comment]
out of curiosity, does this happen with transmission or fragments?

**Comment by egigoka** [comment]
> out of curiosity, does this happen with transmission or fragments?

After updates it doesn’t reproduce anymore. 

And when it was an error - Transmission was working fine.
